extends Node

signal card_played(card: Resource, player: Node)
signal damage_applied(amount: int, source: Node, target: Node, is_crit: bool)
signal heal_applied(amount: int, target: Node)
signal entity_died(entity: Node)
signal status_applied(data: Resource, target: Node)
signal status_removed(data: Resource, target: Node)
signal trophy_imbued(trophy: Resource, mouse: Node)
signal turn_started(actor: Node)
signal turn_ended(actor: Node)
signal biome_entered(biome_data: Resource, seed: int)
signal biome_exited(biome_data: Resource)
signal predator_intent_published(predator: Node, plan: Resource)
signal rest_action_taken(action: StringName)
signal run_started(class_data: Resource, seed: int)
signal run_ended(success: bool)
